apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ia
  labels:
    app: ia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ia
  template:
    metadata:
      labels:
        app: ia
    spec:
      containers:
      - name: ia
        image: iad.ocir.io/idvwdimile8c/aplicacao111623:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ocisecret
---
apiVersion: v1
kind: Service
metadata:
  name: my-ia-svc
  labels:
    app: ia
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: ia
