apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ia  ## Esse nome de Deployment pode ser alterado por sua preferência
  labels:
    app: ia ## Esse nome de Deployment pode ser alterado por sua preferência
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ia  ## Esse nome de Deployment pode ser alterado por sua preferência
  template:
    metadata:
      labels:
        app: ia   ## Esse nome de Deployment pode ser alterado por sua preferência
    spec:
      containers:
      - name: ia  ## Esse nome de Deployment pode ser alterado por sua preferência
        image: region-key.ocir.io/tenancy-namespace/repositório/nome_da_imagem:tag ## Trocar region-key, tenancy-namespace e nome_da_imagem:tag pelas suas informações
        ports:
        - containerPort: 3000  ## Essa porta vai depender de qual porta está sendo exposta sua aplicação
      imagePullSecrets:
      - name: ocisecret
---
apiVersion: v1
kind: Service
metadata:
  name: my-ia-svc  ## Esse nome de Deployment pode ser alterado por sua preferência
  labels:
    app: ia   ## Esse nome de Deployment pode ser alterado por sua preferência
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
  - port: 3000 ## Essa porta vai depender de qual porta está sendo exposta sua aplicação
  selector:
    app: ia   ## Esse nome de Deployment pode ser alterado por sua preferência
